# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/CW305_KYBER/cw305_kyber/cw305_kyber.cache/wt [current_project]
set_property parent.project_path G:/CW305_KYBER/cw305_kyber/cw305_kyber.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/CW305_KYBER [current_project]
update_ip_catalog
set_property ip_output_repo g:/CW305_KYBER/cw305_kyber/cw305_kyber.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files G:/CW305_KYBER/src/kyber/coe/that.coe
add_files G:/CW305_KYBER/src/kyber/coe/phi_rev.coe
add_files G:/CW305_KYBER/src/kyber/coe/invphi_rev.coe
add_files G:/CW305_KYBER/src/kyber/coe/pwphi_rev.coe
add_files G:/CW305_KYBER/src/kyber/coe/shat_ram0.coe
add_files G:/CW305_KYBER/src/kyber/coe/shat_ram1.coe
read_verilog -library xil_defaultlib {
  E:/CW305_KYBER/src/kyber/Kyber_Server.v
  E:/CW305_KYBER/src/kyber/NTT_core_Server.v
  E:/CW305_KYBER/src/kyber/butterfly_Server.v
  G:/CW305_KYBER/src/cw305/cdc_pulse.v
  G:/CW305_KYBER/src/cw305/clocks.v
  G:/CW305_KYBER/src/cw305/cw305_reg_pmul.v
  G:/CW305_KYBER/src/cw305/cw305_usb_reg_fe.v
  E:/CW305_KYBER/src/kyber/decode_Server.v
  E:/CW305_KYBER/src/kyber/decode_keccak.v
  E:/CW305_KYBER/src/kyber/encode_Server.v
  E:/CW305_KYBER/src/kyber/hash_core_Server.v
  G:/CW305_KYBER/src/kyber/kyber_Wrapper.v
  E:/CW305_KYBER/src/kyber/mux4to2.v
  E:/CW305_KYBER/src/kyber/pattern.v
  E:/CW305_KYBER/src/kyber/reduc.v
  G:/CW305_KYBER/src/cw305/cw305_ecc_p256_pmul_top.v
}
read_vhdl -library xil_defaultlib {
  E:/CW305_KYBER/src/kyber/Keccak1600.vhd
  E:/CW305_KYBER/src/kyber/RegisterFDRE.vhd
  E:/CW305_KYBER/src/kyber/Round.vhd
  E:/CW305_KYBER/src/kyber/StateMachine.vhd
  E:/CW305_KYBER/src/kyber/chi.vhd
  E:/CW305_KYBER/src/kyber/iota.vhd
  E:/CW305_KYBER/src/kyber/pi.vhd
  E:/CW305_KYBER/src/kyber/rho.vhd
  E:/CW305_KYBER/src/kyber/theta.vhd
}
read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8.xdc]
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_5/dist_mem_gen_5.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_5/dist_mem_gen_5_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_6/dist_mem_gen_6.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_6/dist_mem_gen_6_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_7/dist_mem_gen_7.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_7/dist_mem_gen_7_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_6/c_shift_ram_6.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_6/c_shift_ram_6_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1_ooc.xdc]

read_ip -quiet G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc]

read_ip -quiet g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2.xci
set_property used_in_implementation false [get_files -all g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/CW305_KYBER/src/cw305/cw305_main.xdc
set_property used_in_implementation false [get_files G:/CW305_KYBER/src/cw305/cw305_main.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cw305_ecc_p256_pmul_top -part xc7a100tftg256-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cw305_ecc_p256_pmul_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cw305_ecc_p256_pmul_top_utilization_synth.rpt -pb cw305_ecc_p256_pmul_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
