# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/CW305_KYBER/src/cw305/cw305_main.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/c_shift_ram_9/c_shift_ram_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_9 || ORIG_REF_NAME==c_shift_ram_9} -quiet] -quiet
