# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xci
# IP: The module: 'fifo_generator_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xci
# IP: The module: 'fifo_generator_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
