# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
# IP: The module: 'c_shift_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
# IP: The module: 'c_shift_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/CW305_KYBER/cw305_kyber/cw305_kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
